/**
 * Author:  Riccardo Balia
 * Created: 11-mag-2016
 */

/*CREAZIONE DELLE TABELLE*/

CREATE TABLE AccountBalance
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    balance DOUBLE
);

CREATE TABLE Seller
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(128),
    surname VARCHAR(128),
    username VARCHAR(128),
    password VARCHAR(128),
    idAccountBalance INTEGER,
    FOREIGN KEY (idAccountBalance) REFERENCES AccountBalance(id)
    
);

CREATE TABLE Customer
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(128),
    surname VARCHAR(128),
    username VARCHAR(128),
    password VARCHAR(128),
    idAccountBalance INTEGER,
    FOREIGN KEY (idAccountBalance) REFERENCES AccountBalance(id)
    
);

CREATE TABLE ObjectSale
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(128),
    imageURL VARCHAR(256),
    description VARCHAR(256),
    price DOUBLE,
    availability INTEGER,
    category VARCHAR(128),
    idSeller INTEGER,
    FOREIGN KEY (idSeller) REFERENCES Seller (id) 
);





/*POPOLAMENTO DELLE TABELLE*/

INSERT INTO ACCOUNTBALANCE (id, balance)
VALUES
(default, 54.8),
(default, 9.4),
(default, 76.1),
(default, 106.6),
(default, 13.5),
(default, 9.7);

INSERT INTO SELLER (id,name,surname,username,password,idAccountBalance)
VALUES
(default, 'Marco','Porcu','markp','pass0',1),
(default, 'Federico','Caddeo','Caddish','pass1',2),
(default, 'Giacomo','Balia','Jack','pass2',3);

INSERT INTO CUSTOMER (id,name,surname,username,password,idAccountBalance)
VALUES
(default, 'Riccardo','Benzoni','Horrorscopo','pass3',4),
(default, 'Fabrizio','Salis','Bixio71','pass4',5),
(default, 'Mauro','Zedda','MauZ','pass5',6);

INSERT INTO OBJECTSALE (id,name,imageURL,description,price,availability,category, idSeller)
VALUES
(default, 'O-Mg','./Immagini/Accendino1.jpg','Accendino a benzina con cromatura scura e stampa OMG!', 18.7 ,14,'lighters',1),
(default, 'Poker','./Immagini/Accendino2.jpg','Accendino a benzina con cromatura scura e stampa con i semi del poker!', 17.9 ,21,'lighters',1),
(default, 'Spectrum','./Immagini/Accendino3.jpg','Accendino a benzina con cromatura a colori tipici della benzina!', 21.5 ,9,'lighters',2),
(default, 'Pietrine','./Immagini/Ricambi1.jpg','Pietrine originali da sostituire a quelle che ne hanno viste troppe!', 0.8 ,56,'accessories',3),
(default, 'Stoppino','./Immagini/Ricambi2.jpg','Cordicella avvolta nel rame ad alto assorbimento!', 0.4 ,47,'accessories',3),
(default, 'Candle','./Immagini/Accessori1.jpg','Accendino a manico lungo per gli universitari dai fornelli vissuti!', 7.9 ,19,'accessories',1);
